<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>high</name>
  <uuid>97729f9b-37ec-405a-b5f7-ccf597614f6d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    number is at least 6
then
    set decision to "High" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
