<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>51dc02d7-b17d-4e98-a282-e96373d8c6b3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Low";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
