<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>612f8796-9b58-4efd-8b68-325ff911587a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set number to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
