<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>say hello</name>
  <uuid>9014ab0f-6ec7-4bf4-8ea7-f366270f0318</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if name is defined then set decision to "Hello " + name + " , welcome to ADS wiv a git push 13.19" ; 
else  set decision to "Hello Stranger" ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
